### ISSUE TITLE
What is the easiest way to simulate our solar system with your toolkit?

### ISSUE THREAD

**Issue by tdowgielewicz** [Karth42/SimpleKeplerOrbits#1]

**Comment by Karth42** [comment]
Can you describe what do you want to achieve? Or give more specific question, please. There are many various approaches in simulating solar systems in games.

**Comment by tdowgielewicz** [comment]
I would like to simulate our solar system (Mars, Venus, Earth, Moon,  Space crafts etc) that all planets move exactly like they do in real life ( Educational purpose ) And simulate time flow. 

Best way would be to add item from JPL Database. 
I'm would like to add feature like this.

**Comment by Karth42** [comment]
This approach requires quite advanced data processing to be made. Originally, this plugin was developed for custom orbits creation by hands, so there are some difficulties in using real world orbits.

Basically, you can add bodies from any database you want, but raw data must be prepared for this.
1) For each body you must provide position and velocity vectors.
2) For each attractor you must provide mass and G const (this constant is not globally shared, but it can be same for each attractor).
3) All input values should be scaled down by some large mlt factor, for example 10e-7, because unity's float precision can't handle large distances.
You can do this in some simple manager class, which will search or spawn all bodies from predefined settings list and feed them init settings.

Main difficulty here is to prepare actual data. JPL database, for example, doesn't provide you ready-to-use positions and velocities vectors, but it provides all other orbital parameters, which may be converted into vectors, but you will need to find or develop proper conversation algorithm.

Internally, SimpleKeplerOrbit plugin uses similar orbital parameters, like eccentricity, semi-major axis, etc., but there is only one default way to set this parameters - assign position and velocity vectors (they converting into orbital parameters on class initialization).
So, in result, orbit parameters from JPL needs to be converted into vectors, which will be then internally converted again back into orbital parameters. Not pretty, but it is how it is.

However, if you are skilled programmer, you can develop your own orbit initialization algorithm, which will use raw data from JPL. But maybe this is not easiest or preferred way. It is possible somewhere you can find better tools for orbit simulation where this feature already present.

And other thing, time control, is quite simple - if scale multiplier of all orbits is same and initial bodies positions selected from exact one time moment, then all motions will be synchronized as long as TimeScale on all bodies remains same. You can change TimeScale whatever you want, even set negative values, but you need to change it same way on all active bodies. A small centralized controller class can handle this.

**Comment by tdowgielewicz** [comment]
Thank you very much.
Hope will create merge request in some mid range future.

Regards,
Tomasz

2018-02-19 18:41 GMT+01:00 Karth42 <notifications@github.com>:

**Comment by Karth42** [comment]
Instead of creating pull request in this repository, please make fork and publish all your changes there (if you will make some).
