### ISSUE TITLE
Invalid orbit

### ISSUE THREAD

**Issue by vinaygodara** [Karth42/SimpleKeplerOrbits#2]
1.Object at stationery position or with zero velocity should be attracted towards the centre of attracter .but this does not happen.

2.Also body mass did not effect orbit ,only attracter mass count for gravity.

3.please add the rigid body velocity  insted of empty distance from parent. 

Although your work is awesome and thanks for Sharing.

**Comment by Karth42** [comment]
hey, thank you for feedback.

1. it is not a bug by design. as primary description states, this simulation plugin **does not** simulate n-body physics. this means all orbits can't change over time, they are static. You need to setup orbit before launch (see my comment in other closed issue).

2. not a bug by design. only attractor's mass affects orbit because this plugin implements simple 2-body solution of orbital motion, which means there is only one attractor in system. 
some additional notes to help you understand the idea:
- when you create some solar system with multiple plantes, each planet and it's orbit is completly separated from each other (multiple separated closed systems).
- if you want to create some complex systems, like binary stars, then you can use invicible barycenter as real attractor and make all stars to move around it in orbits with equal periods (apoapsises must be on opposite sides from barycenter).

3. physics system will never be used in this plugin (rigidbody or colliders components) because it adds unnecesarry dependency on physics system, which affects performance. some project may not use native unity physics at all (if mobile platform, for example). however, nothing stops you from adding physics for yourself.
