### ISSUE TITLE
What is the startup Item

### ISSUE THREAD

**Issue by BicycleMark** [Karth42/SimpleKeplerOrbits#4]
I have downloaded and opened in visual studio. 2017. What item do i set as startup. Visual studio is requiring i set a startup item. Thanks Mark

**Comment by Karth42** [comment]
Hi. This project is a Unity3d project, which means that you need to install Unity editor and open project in it, and then, after Unity will generate a proper solution file, open it in visual studio.
I haven't heard about any required startup item.

If you wish to use code without unity - you can do this. For this you need to create solution from skratch and import some scripts, not all, because there are some dependencies on UnityEngine namespace, which should be manually removed.
